// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxRp7I-aHayfyVt8Vw-HCsiV-yWvBw-U',
    appId: '1:451988423262:web:d5b34943d9121568eaeacf',
    messagingSenderId: '451988423262',
    projectId: 'service-link-c30c1',
    authDomain: 'service-link-c30c1.firebaseapp.com',
    storageBucket: 'service-link-c30c1.appspot.com',
    measurementId: 'G-LQ9S8DR2L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBimNwZdgs9EuJWwHnc7maxMgR9Wg2OD3U',
    appId: '1:451988423262:android:acf05ff6bafcffd4eaeacf',
    messagingSenderId: '451988423262',
    projectId: 'service-link-c30c1',
    storageBucket: 'service-link-c30c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQuRJjVlPOyzWUTXUA_jT97gOuF2XV6Lo',
    appId: '1:451988423262:ios:72df4534f0e6d77feaeacf',
    messagingSenderId: '451988423262',
    projectId: 'service-link-c30c1',
    storageBucket: 'service-link-c30c1.appspot.com',
    iosBundleId: 'com.depi.serviceLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxRp7I-aHayfyVt8Vw-HCsiV-yWvBw-U',
    appId: '1:451988423262:web:44625478460b1471eaeacf',
    messagingSenderId: '451988423262',
    projectId: 'service-link-c30c1',
    authDomain: 'service-link-c30c1.firebaseapp.com',
    storageBucket: 'service-link-c30c1.appspot.com',
    measurementId: 'G-4LHD3G7GPX',
  );
}
